export const MESSAGES_TYPES = {
  RECIVE: {
    ENTITIES_POSITION: 'ENTITIES_POSITION',
    HANDSHAKE: 'HANDSHAKE',
    ROOM_INITIALIZE: 'ROOM_INITIALIZE'
  },
  SEND: {
    HANDSHAKE: 'HANDSHAKE',
    MOVE_UP: 'MOVE_UP',
    MOVE_DOWN: 'MOVE_DOWN',
    MOVE_LEFT: 'MOVE_LEFT',
    MOVE_RIGHT: 'MOVE_RIGHT',
  }
}