export const MESSAGES_TYPES = {
  SEND: {
    ENTITIES_POSITION: 'ENTITIES_POSITION',
    HANDSHAKE: 'HANDSHAKE',
    ROOM_INITIALIZE: 'ROOM_INITIALIZE',
    PLAYER_JOINED_ROOM: 'PLAYER_JOINED_ROOM',
    PLAYER_LEFT_ROOM: 'PLAYER_LEFT_ROOM'

  },
  RECIVED: {
    HANDSHAKE: 'HANDSHAKE',
    MOVE_UP: 'MOVE_UP',
    MOVE_DOWN: 'MOVE_DOWN',
    MOVE_LEFT: 'MOVE_LEFT',
    MOVE_RIGHT: 'MOVE_RIGHT',
  }
};