export const MESSAGES_TYPES = {
  SEND: {
    ENTITIES_POSITION: 'ENTITIES_POSITION',
    HANDSHAKE: 'HANDSHAKE',
    ROOM_INITIALIZE: 'ROOM_INITIALIZE',

  },
  RECIVE: {
    HANDSHAKE: 'HANDSHAKE',
    MOVE_UP: 'MOVE_UP',
    MOVE_DOWN: 'MOVE_DOWN',
    MOVE_LEFT: 'MOVE_LEFT',
    MOVE_RIGHT: 'MOVE_RIGHT',
  }
};